---
# Copyright: Contributors to the Ansible project
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

namespace: waitingatthecrossroads
name: proxmox_virtual_environment
version: 1.0.0
readme: README.md
authors:
  - WaitingAtTheCrossroads <waitingatthecrossroads@proton.me>
description: The best darn Proxmox Virtual Environment automation there ever was!
license_file: LICENSE
tags:
  - infrastructure
  - linux
  - proxmox
  - pve
  - virtualization
  - hypervisor
dependencies:
  ansible.utils: "*"
repository: https://github.com/WaitingAtTheCrossroads/ansible-collections-crossroads-pve
documentation: https://github.com/WaitingAtTheCrossroads/ansible-collections-crossroads-pve/blob/main/README.md
homepage: https://github.com/WaitingAtTheCrossroads/ansible-collections-crossroads-pve
issues: https://github.com/WaitingAtTheCrossroads/ansible-collections-crossroads-pve/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
